(in-package :mu-cl-resources)
(defparameter *cache-model-properties* t)
(defparameter *cache-count-queries* t)
(defparameter *supply-cache-headers-p* t)

(define-resource car ()
  :class (s-prefix "schema:Car")
  :properties `((:brand :string ,(s-prefix "schema:Brand")
                        :required)
                (:model :string ,(s-prefix "schema:ProductModel")
                        :required)
                )
  :resource-base (s-url "http://semte.baert.jp.net/cars/v0.1/")
  :on-path "cars")
